### ISSUE TITLE
Error while running p2prc --UpdateServerList

### ISSUE THREAD

**Issue by benjaminjacobreji** [Akilan1999/p2p-rendering-computation#25]
The error message I'm getting
```
p2prc --UpdateServerList
panic: runtime error: slice bounds out of range [3:2]

goroutine 1 [running]:
git.sr.ht/~akilan1999/p2p-rendering-computation/p2p.(*IpAddresses).SpeedTest(0xc00000e150, 0x0, 0x0)
	/home/asleepyguy/Projects/p2p-rendering-computation/p2p/speedtest.go:49 +0x465
git.sr.ht/~akilan1999/p2p-rendering-computation/p2p.LocalSpeedTestIpTable(0xb82740, 0x0)
	/home/asleepyguy/Projects/p2p-rendering-computation/p2p/speedtest.go:106 +0x3c
git.sr.ht/~akilan1999/p2p-rendering-computation/client.UpdateIpTableListClient(0xc0005ce530, 0x540000c0004ca450)
	/home/asleepyguy/Projects/p2p-rendering-computation/client/Iptable.go:63 +0x37
git.sr.ht/~akilan1999/p2p-rendering-computation/cmd.glob..func1(0xc0004dc640, 0x0, 0x1a)
	/home/asleepyguy/Projects/p2p-rendering-computation/cmd/action.go:21 +0x69b
github.com/urfave/cli/v2.(*App).RunContext(0xc00011e000, 0xd50b28, 0xc00013a030, 0xc000142000, 0x2, 0x2, 0x0, 0x0)
	/home/asleepyguy/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x6fe
github.com/urfave/cli/v2.(*App).Run(...)
	/home/asleepyguy/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/home/asleepyguy/Projects/p2p-rendering-computation/main.go:26 +0x125
```

**Comment by Akilan1999** [comment]
Ah it's an issue with the list manipulations. I will look into it
